/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-categories': ProductCategory;
    'product-subcategories': ProductSubcategory;
    products: Product;
    gallery: Gallery;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    'product-subcategories': ProductSubcategoriesSelect<false> | ProductSubcategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'de') | ('en' | 'fr' | 'de')[];
  globals: {
    'about-page': AboutPage;
    'site-settings': SiteSetting;
    'header-navigation': HeaderNavigation;
    footer: Footer;
    'contact-information': ContactInformation;
    'social-links': SocialLink;
    homepage: Homepage;
  };
  globalsSelect: {
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-navigation': HeaderNavigationSelect<false> | HeaderNavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'contact-information': ContactInformationSelect<false> | ContactInformationSelect<true>;
    'social-links': SocialLinksSelect<false> | SocialLinksSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'en' | 'fr' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    catalog?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  slug: string;
  name: string;
  description?: string | null;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  active?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-subcategories".
 */
export interface ProductSubcategory {
  id: number;
  slug: string;
  name: string;
  parentCategory: number | ProductCategory;
  description?: string | null;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  slug: string;
  name: string;
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: number | ProductCategory;
  subcategory?: (number | null) | ProductSubcategory;
  featuredImage?: (number | null) | Media;
  galleryImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        application: string;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  active?: boolean | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  description?: string | null;
  image: number | Media;
  category:
    | 'bulk-shipments'
    | 'packing-in-bags'
    | 'packing-in-sacks'
    | 'packing-in-sling-jumbo-bags'
    | 'shipping-in-containers';
  sortOrder?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  firstName: string;
  lastName: string;
  company?: string | null;
  address?: string | null;
  city: string;
  country: string;
  phone: string;
  cellPhone: string;
  fax?: string | null;
  email: string;
  website?: string | null;
  interestedIn?: string | null;
  omegaLineProduct?: string | null;
  saltType?: string | null;
  message: string;
  consent: boolean;
  status?: ('new' | 'contacted' | 'closed') | null;
  locale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'product-subcategories';
        value: number | ProductSubcategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        catalog?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  active?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-subcategories_select".
 */
export interface ProductSubcategoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  parentCategory?: T;
  description?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortDescription?: T;
  fullDescription?: T;
  category?: T;
  subcategory?: T;
  featuredImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        application?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  featured?: T;
  active?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  category?: T;
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  company?: T;
  address?: T;
  city?: T;
  country?: T;
  phone?: T;
  cellPhone?: T;
  fax?: T;
  email?: T;
  website?: T;
  interestedIn?: T;
  omegaLineProduct?: T;
  saltType?: T;
  message?: T;
  consent?: T;
  status?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  overviewHeading?: string | null;
  overviewParagraphs?:
    | {
        paragraph?: string | null;
        id?: string | null;
      }[]
    | null;
  overviewImage?: (number | null) | Media;
  historyHeading?: string | null;
  historyParagraphs?:
    | {
        paragraph?: string | null;
        id?: string | null;
      }[]
    | null;
  exportCountries?:
    | {
        country: string;
        id?: string | null;
      }[]
    | null;
  nestleRelationshipText?: string | null;
  missionHeading?: string | null;
  missionText?: string | null;
  visionHeading?: string | null;
  visionText?: string | null;
  certificatesHeading?: string | null;
  certificates?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        active?: boolean | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal source and verification guidance for the About page.
   */
  verificationNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-navigation".
 */
export interface HeaderNavigation {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  summary?: string | null;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-information".
 */
export interface ContactInformation {
  id: number;
  /**
   * Placeholder-safe public contact note.
   */
  notice?: string | null;
  address?: string | null;
  telephoneNumbers?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  faxNumbers?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  cellNumbers?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  emailAddresses?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links".
 */
export interface SocialLink {
  id: number;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroEyebrow?: string | null;
  heroHeading?: string | null;
  heroDescription?: string | null;
  /**
   * Fallback image or video poster.
   */
  heroImage?: (number | null) | Media;
  /**
   * MP4 or WebM hero video. When set, plays instead of the default hero video.
   */
  heroVideo?: (number | null) | Media;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  trustIndicators?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  aboutEyebrow?: string | null;
  aboutHeading?: string | null;
  aboutDescription?: string | null;
  aboutImage?: (number | null) | Media;
  aboutStrengths?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  aboutButtonLabel?: string | null;
  productsEyebrow?: string | null;
  productsHeading?: string | null;
  productsDescription?: string | null;
  featuredProductCategories?: (number | ProductCategory)[] | null;
  industriesHeading?: string | null;
  industriesDescription?: string | null;
  industries?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  qualityEyebrow?: string | null;
  qualityHeading?: string | null;
  qualityBenefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  certificateImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  quoteEyebrow?: string | null;
  quoteHeading?: string | null;
  quoteDescription?: string | null;
  exportHeading?: string | null;
  exportDescription?: string | null;
  statistics?:
    | {
        label: string;
        /**
         * Leave empty until verified.
         */
        value?: number | null;
        suffix?: string | null;
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  galleryHeading?: string | null;
  galleryDescription?: string | null;
  featuredGalleryItems?: (number | Gallery)[] | null;
  finalCtaHeading?: string | null;
  finalCtaDescription?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  overviewHeading?: T;
  overviewParagraphs?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  overviewImage?: T;
  historyHeading?: T;
  historyParagraphs?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  exportCountries?:
    | T
    | {
        country?: T;
        id?: T;
      };
  nestleRelationshipText?: T;
  missionHeading?: T;
  missionText?: T;
  visionHeading?: T;
  visionText?: T;
  certificatesHeading?: T;
  certificates?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        active?: T;
        sortOrder?: T;
        id?: T;
      };
  verificationNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-navigation_select".
 */
export interface HeaderNavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  summary?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-information_select".
 */
export interface ContactInformationSelect<T extends boolean = true> {
  notice?: T;
  address?: T;
  telephoneNumbers?:
    | T
    | {
        number?: T;
        id?: T;
      };
  faxNumbers?:
    | T
    | {
        number?: T;
        id?: T;
      };
  cellNumbers?:
    | T
    | {
        number?: T;
        id?: T;
      };
  emailAddresses?:
    | T
    | {
        email?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeading?: T;
  heroDescription?: T;
  heroImage?: T;
  heroVideo?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  trustIndicators?:
    | T
    | {
        label?: T;
        id?: T;
      };
  aboutEyebrow?: T;
  aboutHeading?: T;
  aboutDescription?: T;
  aboutImage?: T;
  aboutStrengths?:
    | T
    | {
        label?: T;
        id?: T;
      };
  aboutButtonLabel?: T;
  productsEyebrow?: T;
  productsHeading?: T;
  productsDescription?: T;
  featuredProductCategories?: T;
  industriesHeading?: T;
  industriesDescription?: T;
  industries?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  qualityEyebrow?: T;
  qualityHeading?: T;
  qualityBenefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  certificateImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  quoteEyebrow?: T;
  quoteHeading?: T;
  quoteDescription?: T;
  exportHeading?: T;
  exportDescription?: T;
  statistics?:
    | T
    | {
        label?: T;
        value?: T;
        suffix?: T;
        verified?: T;
        id?: T;
      };
  galleryHeading?: T;
  galleryDescription?: T;
  featuredGalleryItems?: T;
  finalCtaHeading?: T;
  finalCtaDescription?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}